### ISSUE TITLE
HttpRequestMessage dependency in tests

### ISSUE THREAD

**Issue by DanCorder** [dcastro/JSendWebApi#2]
Hi, I'm attempting to convert an existing API controller with existing tests to a JSendApiController.

A lot of my tests fail after switching from CreatedAtRoute to JSendCreatedAtRoute results. This appears to be because the JSend results expect the controller to have a request and possibly a URL set too.

Do I need to set up detailed fake requests for my tests (the default CreatedAtRoute result doesn't need this) or can JSendWebApi be changed to work without requests being present?

**Comment by dcastro** [comment]
Thanks for bringing this to my attention.

The `ApiController.CreatedAtRoute` method returns an instance of [`CreatedAtRouteNegotiatedContentResult`][0], whereas `JSendApiController.JSendCreatedAtRoute` returns an instance of [`JSendCreatedAtRouteResult`][1].

It turns out that there's a slight difference between those result types. Both require a request and a UrlHelper, but `CreatedAtRouteNegotiatedContentResult` only checks that these properties are set when [`ExecuteAsync`][2] is called, whereas `JSendCreatedAtRouteResult` does this check in the constructor.

In other words, you can create a `CreatedAtRouteNegotiatedContentResult` without a request/url helper, but you won't be able to execute it. On the other hand, you can't even create a `JSendCreatedAtRouteResult` unless you have a request/url helper.

I'll change this behavior to match that of `CreatedAtRouteNegotiatedContentResult`.

For now, yes, you'll need to setup a fake request/url helper. A new version should be released in a day or two.

Thanks.

 [0]: https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/Results/CreatedAtRouteNegotiatedContentResult.cs
 [1]: https://github.com/dcastro/JSendWebApi/blob/master/src/JSend.WebApi/Results/JSendCreatedAtRouteResult.cs
 [2]: https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/Results/CreatedAtRouteNegotiatedContentResult.cs#L120

**Comment by DanCorder** [comment]
Thanks, that would be great. Presumably the change will also affect the other JSend result types too?

**Comment by dcastro** [comment]
Yes, it will.

**Comment by dcastro** [comment]
Thank you for your feedback. This is now live as [JSend.WebApi 0.7.0](https://www.nuget.org/packages/JSend.WebApi/0.7.0)

**Comment by DanCorder** [comment]
Thanks, I've updated to the new version and have been able to convert my remaining controllers without any issues.
